services:
  - type: web
    name: telegram-all-in-one-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: DEVELOPER_NAME
        sync: false
      - key: DEVELOPER_USERNAME
        sync: false
      - key: DEVELOPER_CHANNEL
        sync: false
